language: node_js
node_js:
  - "0.10"
addons:
  hosts:
    - checkout.namdv.com
install:
  - npm install
  - npm install protractor -g
before_script:
  - "npm start &"
  - "sleep 2"
  - "./BrowserStackLocal.linux64 -v h9DWk1AcK8ygmtDwBezK localhost,8000,0 &"
  - sleep 10
  - "ps -fA | grep node"
  - "ps -fA | grep BrowserStackLocal"
  - "bsPid=`ps -fA | grep BrowserStackLocal | awk '{print $2}'`"
  - "echo -e $bsPid"
script:
  - "protractor test/config.js"
after_script:
  - "ps -fA | grep node"
  - "kill -9 $bsPid"